import { View, Text, FlatList, StyleSheet } from 'react-native';

import styles from './Estilo';

export default function Home({ navigation }) {

    const usuarios = [
    { id: '1', nome: 'João' },
    { id: '2', nome: 'Maria' },
    { id: '3', nome: 'Pedro' },
    { id: '4', nome: 'Ana' },
    { id: '5', nome: 'Carlos' },
    { id: '6', nome: 'Beatriz' },
    { id: '7', nome: 'Lucas' },
    { id: '8', nome: 'Juliana' },
    { id: '9', nome: 'Rafael' },
    { id: '10', nome: 'Camila' },
    { id: '11', nome: 'Gabriel' },
    { id: '12', nome: 'Larissa' },
    { id: '13', nome: 'Mateus' },
    { id: '14', nome: 'Mariana' },
    { id: '15', nome: 'Felipe' },
    { id: '16', nome: 'Amanda' },
    { id: '17', nome: 'Bruno' },
    { id: '18', nome: 'Bianca' },
    { id: '19', nome: 'Gustavo' },
    { id: '20', nome: 'Isabela' },
    { id: '21', nome: 'Rodrigo' },
    { id: '22', nome: 'Carolina' },
    { id: '23', nome: 'Daniel' },
    { id: '24', nome: 'Fernanda' },
    { id: '25', nome: 'Leonardo' },
    { id: '26', nome: 'Patrícia' },
    { id: '27', nome: 'Thiago' },
    { id: '28', nome: 'Renata' },
    { id: '29', nome: 'André' },
    { id: '30', nome: 'Letícia' },
    { id: '31', nome: 'Marcelo' },
    { id: '32', nome: 'Vanessa' },
    { id: '33', nome: 'Eduardo' },
    { id: '34', nome: 'Natália' },
    { id: '35', nome: 'Ricardo' },
    { id: '36', nome: 'Priscila' },
    { id: '37', nome: 'Alexandre' },
    { id: '38', nome: 'Tatiane' },
    { id: '39', nome: 'Diego' },
    { id: '40', nome: 'Cristiane' },
    { id: '41', nome: 'Fernando' },
    { id: '42', nome: 'Aline' },
    { id: '43', nome: 'Roberto' },
    { id: '44', nome: 'Débora' },
    { id: '45', nome: 'Fábio' },
    { id: '46', nome: 'Simone' },
    { id: '47', nome: 'Márcio' },
    { id: '48', nome: 'Elaine' },
    { id: '49', nome: 'Vinícius' },
    { id: '50', nome: 'Carla' },
    { id: '51', nome: 'Henrique' },
    { id: '52', nome: 'Mônica' },
    { id: '53', nome: 'Wagner' },
    { id: '54', nome: 'Flávia' },
    { id: '55', nome: 'Igor' },
    { id: '56', nome: 'Viviane' },
    { id: '57', nome: 'Samuel' },
    { id: '58', nome: 'Cíntia' },
    { id: '59', nome: 'Jorge' },
    { id: '60', nome: 'Sabrina' },
    { id: '61', nome: 'Alex' },
    { id: '62', nome: 'Raquel' },
    { id: '63', nome: 'Caio' },
    { id: '64', nome: 'Débora' },
    { id: '65', nome: 'Otávio' },
    { id: '66', nome: 'Luana' },
    { id: '67', nome: 'Vitor' },
    { id: '68', nome: 'Evelyn' },
    { id: '69', nome: 'Murilo' },
    { id: '70', nome: 'Nicole' },
    { id: '71', nome: 'Pablo' },
    { id: '72', nome: 'Manuela' },
    { id: '73', nome: 'Arthur' },
    { id: '74', nome: 'Clara' },
    { id: '75', nome: 'Enzo' },
    { id: '76', nome: 'Valentina' },
    { id: '77', nome: 'Bernardo' },
    { id: '78', nome: 'Helena' },
    { id: '79', nome: 'Davi' },
    { id: '80', nome: 'Laura' },
    { id: '81', nome: 'Heitor' },
    { id: '82', nome: 'Alice' },
    { id: '83', nome: 'Lorenzo' },
    { id: '84', nome: 'Sophia' },
    { id: '85', nome: 'Miguel' },
    { id: '86', nome: 'Valéria' },
    { id: '87', nome: 'Breno' },
    { id: '88', nome: 'Yasmin' },
    { id: '89', nome: 'Nicolas' },
    { id: '90', nome: 'Melissa' },
    { id: '91', nome: 'Joaquim' },
    { id: '92', nome: 'Lívia' },
    { id: '93', nome: 'Vicente' },
    { id: '94', nome: 'Cecília' },
    { id: '95', nome: 'Tomás' },
    { id: '96', nome: 'Maitê' },
    { id: '97', nome: 'Antônio' },
    { id: '98', nome: 'Esther' },
    { id: '99', nome: 'Francisco' },
    { id: '100', nome: 'Olívia' },

    { id: '101', nome: 'José' },
    { id: '102', nome: 'Sofia' },
    { id: '103', nome: 'Manoel' },
    { id: '104', nome: 'Lorena' },
    { id: '105', nome: 'Rogério' },
    { id: '106', nome: 'Adriana' },
    { id: '107', nome: 'Sérgio' },
    { id: '108', nome: 'Luciana' },
    { id: '109', nome: 'Cláudio' },
    { id: '110', nome: 'Regina' },
    { id: '111', nome: 'Cristiano' },
    { id: '112', nome: 'Silvana' },
    { id: '113', nome: 'Elias' },
    { id: '114', nome: 'Tereza' },
    { id: '115', nome: 'Evandro' },
    { id: '116', nome: 'Rosana' },
    { id: '117', nome: 'César' },
    { id: '118', nome: 'Joana' },
    { id: '119', nome: 'Edson' },
    { id: '120', nome: 'Márcia' },
    { id: '121', nome: 'Alberto' },
    { id: '122', nome: 'Sandra' },
    { id: '123', nome: 'Ronaldo' },
    { id: '124', nome: 'Denise' },
    { id: '125', nome: 'Adriano' },
    { id: '126', nome: 'Elaine' },
    { id: '127', nome: 'Wilson' },
    { id: '128', nome: 'Cristina' },
    { id: '129', nome: 'Nelson' },
    { id: '130', nome: 'Vera' },
    { id: '131', nome: 'Osvaldo' },
    { id: '132', nome: 'Irene' },
    { id: '133', nome: 'Gilberto' },
    { id: '134', nome: 'Marlene' },
    { id: '135', nome: 'Hélio' },
    { id: '136', nome: 'Nádia' },
    { id: '137', nome: 'Augusto' },
    { id: '138', nome: 'Silvia' },
    { id: '139', nome: 'Leandro' },
    { id: '140', nome: 'Vivian' },
    { id: '141', nome: 'Cauã' },
    { id: '142', nome: 'Isis' },
    { id: '143', nome: 'Nathan' },
    { id: '144', nome: 'Ariane' },
    { id: '145', nome: 'Jonathan' },
    { id: '146', nome: 'Tainá' },
    { id: '147', nome: 'Erick' },
    { id: '148', nome: 'Jéssica' },
    { id: '149', nome: 'Wesley' },
    { id: '150', nome: 'Karina' },

    { id: '151', nome: 'Yuri' },
    { id: '152', nome: 'Priscila' },
    { id: '153', nome: 'Alan' },
    { id: '154', nome: 'Débora' },
    { id: '155', nome: 'Cauê' },
    { id: '156', nome: 'Elaine' },
    { id: '157', nome: 'Ruan' },
    { id: '158', nome: 'Mirela' },
    { id: '159', nome: 'Bryan' },
    { id: '160', nome: 'Giovana' },
    { id: '161', nome: 'Kevin' },
    { id: '162', nome: 'Eduarda' },
    { id: '163', nome: 'Ryan' },
    { id: '164', nome: 'Gabriela' },
    { id: '165', nome: 'Nathaniel' },
    { id: '166', nome: 'Isadora' },
    { id: '167', nome: 'Erick' },
    { id: '168', nome: 'Luiza' },
    { id: '169', nome: 'Bento' },
    { id: '170', nome: 'Heloísa' },
    { id: '171', nome: 'Benício' },
    { id: '172', nome: 'Rebeca' },
    { id: '173', nome: 'Théo' },
    { id: '174', nome: 'Sarah' },
    { id: '175', nome: 'Gael' },
    { id: '176', nome: 'Agatha' },
    { id: '177', nome: 'Noah' },
    { id: '178', nome: 'Malu' },
    { id: '179', nome: 'Luan' },
    { id: '180', nome: 'Emanuelly' },
    { id: '181', nome: 'Caleb' },
    { id: '182', nome: 'Rafaela' },
    { id: '183', nome: 'Isaac' },
    { id: '184', nome: 'Emilly' },
    { id: '185', nome: 'Matias' },
    { id: '186', nome: 'Catarina' },
    { id: '187', nome: 'Dante' },
    { id: '188', nome: 'Aurora' },
    { id: '189', nome: 'Romeu' },
    { id: '190', nome: 'Amélia' },
    { id: '191', nome: 'Salvador' },
    { id: '192', nome: 'Luna' },
    { id: '193', nome: 'Estevão' },
    { id: '194', nome: 'Elisa' },
    { id: '195', nome: 'Valentim' },
    { id: '196', nome: 'Madalena' },
    { id: '197', nome: 'Cristóvão' },
    { id: '198', nome: 'Bárbara' },
    { id: '199', nome: 'Domingos' },
    { id: '200', nome: 'Emanuela' },
    ];

    return (
        <View style={styles.container}>

            <Text style={styles.titulo}>Bem-vindo!</Text>

            <Text style={styles.subtitulo}>Lista de usuários:</Text>

            <FlatList
                data={usuarios}
                keyExtractor={(item) => item.id}
                renderItem={({ item }) => (
                    <View style={styles.item}>
                        <Text style={styles.nome}>{item.nome}</Text>
                    </View>
                )}
            />

        </View>
    );
}